[build]
  command = "npm run build"
  publish = "dist" 

[build.environment]
  NODE_VERSION = "18"
  # ทำให้ Tailwind Typography plugin ถูกติดตั้งอย่างถูกต้องบน Netlify
  NPM_FLAGS = "--prefix=/dev/null"

# ==========================================================
# ส่วนของการ Redirects และ Headers
# Netlify จะอ่านค่าจากที่นี่ก่อนไฟล์ _headers
# ==========================================================

# กฎการ Redirect สำหรับจัดการหน้า 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers ทั้งหมด ถูกย้ายมาจัดการที่นี่เพื่อรวมศูนย์
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Content Security Policy (CSP) ที่สมบูรณ์
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https://hgzbgpbmymoiwjpaypvl.supabase.co; font-src 'self' data: https://cdnjs.cloudflare.com; connect-src 'self' https://hgzbgpbmymoiwjpaypvl.supabase.co; frame-ancestors 'none';"